apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-gpu
  labels:
    app: ollama
spec:
  replicas: 1  # Forcing to 1 so we can seed
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
      - name: ollama
        image: ollama/ollama:0.1.32
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "4Gi"
        ports:
        - containerPort: 11434
          name: ollama-api
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-storage