apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-gpu
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      # REMOVE nodeSelector and tolerations for cloud.google.com/gke-spot
      containers:
      - name: ollama
        image: ollama/ollama:0.1.32
        resources:
          limits:
            cpu: "1"      # Use 1 core for a reliable pull
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
        ports:
        - containerPort: 11434
          name: ollama-api
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-storage